feat: select db instances by tags
qonto/prometheus-rds-exporter pull request #232
Opened 2024-11-29 21:02 UTC by msvticket

fixes #94

2024-12-02 14:00 UTC, msvticket commented
I thought I was basically finished with this PR, but during testing I realised serious limitations in tag selection since configuration of prometheus-rds-exporter is done using viper which isn't case sensitive: https://github.com/spf13/viper/issues/1014

This means that you can only select tags where keys and values are lower case, which isn't a convention most use.

I don't see how to get around this issue while keeping viper. Maybe switch to [koanf](https://github.com/knadh/koanf?tab=readme-ov-file#alternative-to-viper)?

2024-12-02 22:55 UTC, msvticket commented
So, that's what I did: switched to koanf for configuration

2024-12-02 23:32 UTC, msvticket commented
@dcupif @qfritz  Can this be reviewed please?

2024-12-03 08:37 UTC, qfritz commented
We'll have a look. 👀

2024-12-03 09:09 UTC, msvticket commented
I now realised that so far I haven't implemented any limitation of which metrics are fetched from CloudWatch. I can look into that if you like.

2024-12-03 13:39 UTC, jbourdale requested changes
Hello @msvticket. 
Thanks for this contribution! This feature is definitely needed!
I've added some recommendations as comment

2024-12-03 13:39 UTC, jbourdale commented on internal/app/rds/rds.go
> +	}
Can we move this part in a dedicated function ? To improve readability

2024-12-03 13:39 UTC, jbourdale commented on internal/app/rds/rds_test.go
>  	expectedAge := time.Since(*rdsInstance.InstanceCreateTime)
Could you add a test case for tag selection please?

2024-12-03 13:39 UTC, jbourdale commented on README.md
> +| tag-selections           | Tags to select database instances with                |                         |
Can this addition be moved on top on `debug` flag please?

2024-12-03 13:39 UTC, jbourdale commented on README.md
> +| tag-selections           | Tags to select database instances with                |                         |
```suggestion
| tag-selections           | Tags to select database instances with. See [configuration on TagFilters field](https://docs.aws.amazon.com/sdk-for-go/api/service/resourcegroupstaggingapi/#GetResourcesInput)               |                         |
```

2024-12-03 13:39 UTC, jbourdale commented on configs/prometheus-rds-exporter/prometheus-rds-exporter.yaml
> +# Select AWS instances by tags
Can be nice to add here too the link to the configuration example (https://docs.aws.amazon.com/sdk-for-go/api/service/resourcegroupstaggingapi/#GetResourcesInput)

2024-12-03 13:39 UTC, jbourdale commented on configs/prometheus-rds-exporter/prometheus-rds-exporter.yaml
> +# Select AWS instances by tags
Can be nice to add here too the link to the configuration example (https://docs.aws.amazon.com/sdk-for-go/api/service/resourcegroupstaggingapi/#GetResourcesInput)

2024-12-11 09:22 UTC, msvticket commented on internal/app/rds/rds.go
> +	}
OK

2024-12-11 09:23 UTC, msvticket commented on internal/app/rds/rds_test.go
>  	expectedAge := time.Since(*rdsInstance.InstanceCreateTime)
What would I test? The selection of resources based on tags are made at AWS...

2024-12-11 09:42 UTC, msvticket commented on README.md
> +| tag-selections           | Tags to select database instances with                |                         |
OK. But I'll use a link to more readable documentation

2024-12-11 09:42 UTC, msvticket commented on configs/prometheus-rds-exporter/prometheus-rds-exporter.yaml
> +# Select AWS instances by tags
OK. But I'll use a link to more readable documentation

2025-01-13 13:39 UTC, BaCaRoZzo commented
@jbourdale any chance this is reviewed in the near future?

2025-02-04 22:10 UTC, msvticket commented
Ping @qfritz Can this be reviewed please?

2025-02-06 10:14 UTC, qfritz commented
I'll have a look in the next few days. Sorry about the delay.

2025-02-07 11:08 UTC, qfritz approved these changes
Will release a RC first to test it too.

2025-02-07 11:36 UTC, msvticket commented
> Will release a RC first to test it too.

Sounds good. I have built an image from my PR that I have used in a couple of clusters for 2 months.

2025-02-07 13:11 UTC, qfritz commented
Hi @msvticket, could you please sign your commits so we can safely merge this? Our security standard on this repository has this layer enabled.

2025-02-07 13:26 UTC, msvticket commented
> Hi @msvticket, could you please sign your commits so we can safely merge this? Our security standard on this repository has this layer enabled.

They are already signed

2025-02-07 13:29 UTC, msvticket commented
As in that the DCO is succeeding. What do you mean?

2025-02-07 13:38 UTC, merged

2025-02-07 13:40 UTC, qfritz commented
I'll look at this DCO bot because it's indeed confusing (and github message doesn't help either). Thank you! 
Creating the RC now. 👍

2025-02-07 14:08 UTC, qfritz commented
`v0.12.0-beta.1` is out, I'll test it this afternoon and promote it to `0.12.0` once all clear.

2025-02-10 12:49 UTC, qfritz commented
Ah, I was using the env var [as described here](https://github.com/qonto/prometheus-rds-exporter?tab=readme-ov-file#configuration) instead of helm values. I'll try that instead. Thanks!